In [6]:
import numpy as np

a=np.random.randint(1,100,15)
a

array([26, 96, 73, 29, 52, 55, 83, 10, 98, 74, 20, 73, 23, 17,  6],
      dtype=int32)

In [7]:
#2D
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[11, 23, 37, 79],
       [79, 47, 70, 58],
       [82, 81, 66, 39],
       [33, 29, 49, 82],
       [42, 22, 88, 47],
       [33, 97, 52, 50]], dtype=int32)

In [8]:
#sort
print(np.sort(a))

#descending
print(np.sort(a)[::-1])
a

[ 6 10 17 20 23 26 29 52 55 73 73 74 83 96 98]
[98 96 83 74 73 73 55 52 29 26 23 20 17 10  6]


array([26, 96, 73, 29, 52, 55, 83, 10, 98, 74, 20, 73, 23, 17,  6],
      dtype=int32)

In [9]:
#2D
np.sort(b)

array([[11, 23, 37, 79],
       [47, 58, 70, 79],
       [39, 66, 81, 82],
       [29, 33, 49, 82],
       [22, 42, 47, 88],
       [33, 50, 52, 97]], dtype=int32)

In [12]:
#axis=1-----Default---Sorts elements across each row independently.
np.sort(b,axis=1)

array([[11, 23, 37, 79],
       [47, 58, 70, 79],
       [39, 66, 81, 82],
       [29, 33, 49, 82],
       [22, 42, 47, 88],
       [33, 50, 52, 97]], dtype=int32)

In [11]:
b

array([[11, 23, 37, 79],
       [79, 47, 70, 58],
       [82, 81, 66, 39],
       [33, 29, 49, 82],
       [42, 22, 88, 47],
       [33, 97, 52, 50]], dtype=int32)

In [13]:
#Sorts elements down each column independently.
np.sort(b,axis=0)

array([[11, 22, 37, 39],
       [33, 23, 49, 47],
       [33, 29, 52, 50],
       [42, 47, 66, 58],
       [79, 81, 70, 79],
       [82, 97, 88, 82]], dtype=int32)