In [2]:
#convert 1d in , 2d in 3d array using expand_dims

import numpy as np

a=np.arange(10)
print(a.shape)
print(a)

np.expand_dims(a,axis=0)
print(np.expand_dims(a,axis=0).shape)
print(np.expand_dims(a,axis=0))

(10,)
[0 1 2 3 4 5 6 7 8 9]
(1, 10)
[[0 1 2 3 4 5 6 7 8 9]]


In [3]:
b=np.arange(10,20).reshape(5,2)
print(b.shape)

np.expand_dims(b,axis=0)
print(np.expand_dims(b,axis=0).shape)
print(np.expand_dims(b,axis=0))

(5, 2)
(1, 5, 2)
[[[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]
