In [6]:
import numpy as np


In [7]:
a= np.array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [8]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 1,  6,  7, 10, 12]),)

In [10]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([11,  0, 28, 50, 38, 37,  0,  0,  5, 30,  0,  9,  0,  2, 21])

In [11]:
np.where(a%2 == 0,0,a)

array([11, 53,  0,  0,  0, 37,  0,  0,  5,  0,  0,  9,  0,  0, 21])

In [14]:
matrix = np.array([[8,4],
    [9, 2]
])

# Find rows and columns where elements equal 9 or 8
rows, cols = np.where(matrix > 5)

print("Rows:", rows)  # Output: [0, 1]
print("Cols:", cols)  # Output: [0, 0]
# The values match positions (0,1) and (0,0)


Rows: [0 1]
Cols: [0 0]
